name: Algolia Recrawl

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  ALGOLIA_APP_ID: ${{vars.ALGOLIA_APP_ID}}
  ALGOLIA_API_KEY: ${{vars.ALGOLIA_API_KEY}}
  ALGOLIA_INDEX_NAME: ${{vars.ALGOLIA_INDEX_NAME}}
  MIXPANEL_PROJECT_TOKEN: ${{vars.MIXPANEL_PROJECT_TOKEN}}

jobs:
  algolia_recrawl:
    name: Algolia Recrawl
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # We don't know when the site will be deployed, we just wait a few seconds
      # Better solutions can be found
      - name: Sleep for 30s
        run: sleep 30

      - name: Vercel-MAIN => Algolia crawler creation and recrawl on preview (Push on Main branch)
        uses: algolia/algoliasearch-crawler-github-actions@v1
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ vars.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ vars.ALGOLIA_API_KEY }}
          crawler-name: ${{ secrets.CRAWLER_NAME }}
          site-url: ${{ vars.SITE_URL }}
